# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
