# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('caption', models.TextField(default=b'')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Class')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Project')),
            ],
        ),
    ]
