# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160128_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
