# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160128_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date'),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date'),
        ),
    ]
