# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image_is_index_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date'),
        ),
    ]
