# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_image_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='_class',
            new_name='my_class',
        ),
    ]
